name: Build Electron App for Windows

on:
  push:
    branches:
      - simple
  pull_request:

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Electron app
        run: |
            $electronVersion = (npx electron --version).TrimStart("v")
            npx electron-packager . ExampleApp --electron-version "$electronVersion" `
                --out=dist --overwrite `
                --ignore="^^(?!main||node_modules||package.json||package.json||package-lock.json||.*/main||.*/node_modules||.*/package.json||.*/package.json||.*/package-lock.json)(.+)$"

        shell: pwsh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/**/*.exe
